language: python
python:
- '3.6'
script: ./unittests
deploy:
  provider: lambda
  function_name: certInfo
  region: us-east-1
  role: arn:aws:iam::980316180835:role/lambda_techem_skill
  runtime: python3.6
  handler_name: lambda_handler
  zip: ./src
  on:
    branch: master
  access_key_id: AKIAJC4OTPBSMBJD4ZBA
  secret_access_key: 
    secure: SDBeVMkmtds2ehrsL+JorEkp9sP3CdU4bVnKsVmKuytBlj6MWYqLF5fvjgPSZzwZczrcz7RTnNEWbkNNRiyUzEjQzSFlPw71+T+FQNXi0yTknBk4C3VGCShXDgMcVfTOqbT/7cwN1qR1T2XJns4VaJWJ/qdbGPN8071YVsW80t1Ht2y3PH7Jz93VG2+9WgrFOYR2DCTepV0kCBZDvHhkHmz2tmpzaHU27aabh5ar4orPnxlYvX22ZDsWbjak+M7BG2wZz2zEjFYazbXZAuqr80x6zIQ1UpXNEagpjuSfc6v/ghBk7Jo9wc01TKM3Hfi1c0XBqLjp/7/4ibF6/0gSpXCgBSuLboY4M+N9GrTnNC7EBj5lmmb++NCYaqvd4A+T8j07+OkKHKwL+V1/ESy/nqqY70PnpGjR6J+6ikxRbVGiEySZCOVAENdRferxPOmhy++QcXzNy4xX4rn1ow6VOaL+pil3/94JIJ3hXMP3ru16oOZnbhpG1bWQmOa13GV6s5aU8fsNmj94mbtRNXhM1MVQZZAqmRwIZ9/9f2vPQc74BUOQUN4cmRh7ECDq60ypOrVg/hj1ZQ9dUsdf5mrjT28Ep7jbiBREz8c2LS84vRmz9RJa7efDqs1dYQBiQUkX9XEFeH/X3G8jymzOzLT3mKwZsYQ8VnsMAa7pCVpWywI=
