language: python
python:
- '3.6'
script: "./unittests"
deploy:
  provider: lambda
  function_name: certInfo
  region: us-east-1
  role: arn:aws:iam::980316180835:role/lambda_techem_skill
  runtime: python3.6
  handler_name: lambda_handler
  zip: "./src"
  publish: true
  on:
    branch: master
  access_key_id: AKIAJVL7HOWIC6CIKFSA
  secret_access_key:
    secure: KAoUiZnGFCyt7iX9Jn1abABqnJznSE5QDec7dm55qAQrS9Vvs2wdXR/LXI7oCgygZdRekwDOwOvc2eFxkxVld3ImeXiFvyqprCBljm0JNYCixBjeQgiRDOiHfj7Wtrd5un4QmoTzSiA3SWmywN6AmVcLKaxVY23AUkNBf6hsZL9zuboIjwG9g5mU2oCxY6WaEMnNqMYVDUmglVt2adP4BQF8QBcH3O9X3HQn2+ebEWzeh1HZ1iOsZZAPSbnqj6qIpQKxD4YxKzeXH4BPaZVGvMfGm5SlMJqbluAUDy7e6drfRTEhUA+IAfaxkLWgdWPbXblrq/LftqvajPxBXnUw57B2elUhYpaZcd1JqAZh6s1n2Z54DYoSW6ge0n4ZlvtEIVgVudOYp0n7QZ+5IrhsILtxa1DAaspP1bDGVfxwLbYwRh//Q1LJ+HhP9/YWxF8DwmbthtBtbSLWMy8P/ETD/T7T93Oyf4bYTlVq7LKc8qXcGeg2iSChVE0xn9J9kPBRHHGvkCXZc4+EXMLeMqNKsImNiSDOzMYdKKuV8D4ckvi221ohjRR/nlqglUSmjKVTKlVv2gj9XaNpoUqcZ367djLwodIpX+eDLOHmzXx/nmTDDh+L0DJ1PqQnn0ELqf8v/ivp38pcq+ddh21SQcgsspQiAIiRrIo17ODp8gC5PZI=
